### ISSUE TITLE
fatal error: 'tree_sitter/api.h' file not found

### ISSUE THREAD

**Issue by asalvi0** [tree-sitter/go-tree-sitter#2]
Getting this error using `v0.23.0` via `go get github.com/tree-sitter/go-tree-sitter@latest`:

```
# github.com/tree-sitter/go-tree-sitter
../../go/pkg/mod/github.com/tree-sitter/go-tree-sitter@v0.23.0/allocator.go:5:10: fatal error: 'tree_sitter/api.h' file not found
    5 | #include <tree_sitter/api.h>
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

This is because the tag `v0.23.0` points to a [commit](https://github.com/tree-sitter/go-tree-sitter/tree/v0.23.0) that precedes the latest changes, where this is already fixed:

```
/*
#cgo CFLAGS: -I${SRCDIR}/tree-sitter/lib/include -I${SRCDIR}/tree-sitter/lib/src -std=c11
#include <tree_sitter/api.h>
#include "allocator.h"
*/
```

**Solution:**
- Create a new tag (`v0.23.1`) to the latest commit in `master`.
- Or temporarily use `go get github.com/tree-sitter/go-tree-sitter@master` to use the latest commit.

**Comment by amaanq** [comment]
yes I'm aware (and sorry) - a new tag will come out today w/ the fix

**Comment by amaanq** [comment]
0.23.1 is out
